# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-codegen:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nuget/setup-nuget@v1

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: yarn install
      run: yarn install

    - name: NuGet restore
      run: nuget restore example\windows\example.sln

    - name: run CodeGen
      run: dotnet run -verbose -winmd $env:USERPROFILE\.nuget\packages\microsoft.ui.xaml\2.7.0\lib\uap10.0\Microsoft.UI.Xaml.winmd
      working-directory: package\Codegen

    - name: build TS
      run: yarn build

    - name: verify no changes from CodeGen
      shell: powershell
      run: |
        $changed = git status --porcelain=v1
        if ($changed -ne $null) { throw "CodeGen detected changes" }

  publish-npm:
    runs-on: ubuntu-latest
    needs: run-codegen

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - name: yarn install
      run: yarn install

    - name: build TS
      run: yarn build

    - name: publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      working-directory: package
        
    - name: upload npm logs
      uses: actions/upload-artifact@v2.3.1
      with:
        name: npm-logs
        path: /home/runner/.npm/_logs
      continue-on-error: true
      if: always()
